/**
 * PPTX Export — each widget becomes a slide
 */
import PptxGenJS from 'pptxgenjs';
import html2canvas from 'html2canvas';

export async function exportToPPTX(
  elementId: string,
  dashboardName: string,
  widgetTitles: string[]
): Promise<void> {
  const pptx = new PptxGenJS();
  pptx.defineLayout({ name: 'WIDE', width: 13.33, height: 7.5 });
  pptx.layout = 'WIDE';

  // Title slide
  const titleSlide = pptx.addSlide();
  titleSlide.addText(dashboardName, {
    x: 0.5, y: 2.5, w: 12, h: 1.5,
    fontSize: 36, bold: true, color: '1e293b',
    align: 'center',
  });
  titleSlide.addText(`Generated by VisoryBI • ${new Date().toLocaleDateString()}`, {
    x: 0.5, y: 4.2, w: 12, h: 0.5,
    fontSize: 14, color: '64748b', align: 'center',
  });

  // Capture each widget card
  const container = document.getElementById(elementId);
  if (!container) {
    throw new Error('Dashboard element not found');
  }

  const widgetElements = container.querySelectorAll('[data-widget-id], .recharts-responsive-container');
  const cards = container.querySelectorAll('.glass-card, [class*="ChartCard"]');

  // Fallback: capture entire dashboard as one slide
  const targets = cards.length > 0 ? Array.from(cards) : widgetElements.length > 0 ? Array.from(widgetElements) : [container];

  for (let i = 0; i < Math.min(targets.length, 20); i++) {
    const el = targets[i] as HTMLElement;
    try {
      const canvas = await html2canvas(el, {
        scale: 2,
        useCORS: true,
        logging: false,
        backgroundColor: '#ffffff',
      });

      const imgData = canvas.toDataURL('image/png');
      const slide = pptx.addSlide();

      // Title
      const title = widgetTitles[i] || `Widget ${i + 1}`;
      slide.addText(title, {
        x: 0.5, y: 0.3, w: 12, h: 0.6,
        fontSize: 18, bold: true, color: '1e293b',
      });

      // Chart image
      const imgWidth = 11;
      const imgHeight = (canvas.height / canvas.width) * imgWidth;
      slide.addImage({
        data: imgData,
        x: 1, y: 1.2,
        w: imgWidth,
        h: Math.min(imgHeight, 5.5),
      });
    } catch {
      // Skip widgets that fail to render
    }
  }

  await pptx.writeFile({ fileName: `${dashboardName}-${new Date().toISOString().split('T')[0]}.pptx` });
}
